### PR TITLE
food-olive-oil

### PR DESCRIPTION
**Pull request by Szeraax**

### CODE REVIEW

**Comment by vabene1111** [comment]
unit would me "ml" for metric, everything fluid is usually given in ml or l but most common ml

**Comment by Szeraax** [comment]
Do you buy it by the ml? Or by the l?

**Comment by Szeraax** [comment]
Still need someone to do a sanity check by comparing nutritional content of their at home extra virgin olive oil to this data.

**Comment by vabene1111** [comment]
> Do you buy it by the ml? Or by the l?

usually everything except drinks is bought in ml although i am sure i forgot exceptions here

**Comment by Szeraax** [comment]
add food-olive-oil

**Pull request merged**
